name: GN2_open_data_FA3

model:
  lrs_config:
    initial: 1e-7
    max: 5e-4
    end: 1e-5
    pct_start: 0.01
    weight_decay: 1e-5

  model:
    class_path: salt.models.SaltModel
    init_args:
      init_nets:
        - input_name: tracks
          dense_config:
            output_size: &embed_dim 256
            hidden_layers: [256]
            activation: &activation ReLU

      encoder:
        class_path: salt.models.Transformer
        init_args:
          num_layers: 4
          embed_dim: *embed_dim
          out_dim: &out_dim 128
          attn_type: flash3-varlen
          norm: LayerNorm
          do_final_norm: True
          dense_kwargs:
            activation: *activation
            gated: False
          attn_kwargs:
            num_heads: 8
            dropout: 0.0

      pool_net:
        class_path: salt.models.GlobalAttentionPooling
        init_args: { input_size: *out_dim }

      tasks:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.ClassificationTask
              init_args:
                name: jets_classification
                input_name: jets
                label: flavour_label
                use_class_dict: True
                loss:
                  class_path: torch.nn.CrossEntropyLoss
                dense_config: &task_dense_config
                  input_size: *out_dim
                  output_size: 4
                  hidden_layers: [128, 64, 32]
                  activation: *activation

            - class_path: salt.models.ClassificationTask
              init_args:
                name: track_origin
                input_name: tracks
                label: ftagTruthOriginLabel
                weight: 0.5
                use_class_dict: True
                loss: torch.nn.CrossEntropyLoss
                dense_config:
                  <<: *task_dense_config
                  output_size: 8
                  context_size: *out_dim

            - class_path: salt.models.VertexingTask
              init_args:
                name: track_vertexing
                input_name: tracks
                label: ftagTruthVertexIndex
                weight: 1.5
                loss:
                  class_path: torch.nn.BCEWithLogitsLoss
                  init_args: { reduction: none }
                dense_config:
                  <<: *task_dense_config
                  input_size: 256
                  output_size: 1
                  context_size: *out_dim

data:
  variables:
    jets:
      - pt_btagJes
      - eta_btagJes
    tracks:
      - d0
      - z0SinTheta
      - dphi
      - deta
      - qOverP
      - lifetimeSignedD0Significance
      - lifetimeSignedZ0SinThetaSignificance
      - phiUncertainty
      - thetaUncertainty
      - qOverPUncertainty
      - numberOfPixelHits
      - numberOfSCTHits
      - numberOfInnermostPixelLayerHits
      - numberOfNextToInnermostPixelLayerHits
      - numberOfInnermostPixelLayerSharedHits
      - numberOfInnermostPixelLayerSplitHits
      - numberOfPixelSharedHits
      - numberOfPixelSplitHits
      - numberOfSCTSharedHits

  train_file: /e/fscratch/reformo/khan27_jupiter/jetset-93940-preprocessing/full/output/pp_output_train.h5
  val_file: /e/fscratch/reformo/khan27_jupiter/jetset-93940-preprocessing/full/output/pp_output_val.h5
  norm_dict: /e/fscratch/reformo/khan27_jupiter/jetset-93940-preprocessing/full/output/norm_dict.yaml
  class_dict: /e/fscratch/reformo/khan27_jupiter/jetset-93940-preprocessing/full/output/class_dict.yaml

  batch_size: 3000
  num_workers: 40

trainer:
  max_epochs: 40

  accelerator: gpu
  devices: 1
  precision: 16-mixed

  default_root_dir: /e/fscratch/reformo/khan27_jupiter/salt-runs/GN2_open_data_FA3

  logger: false

  callbacks:
    - class_path: salt.callbacks.Checkpoint
      init_args:
        monitor_loss: val/jets_classification_loss

    - class_path: lightning.pytorch.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 50

    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 2

